authority/urls.py
from django.urls import path


app_name='authority'

from authority.views import authority_main
from authority.views import manage_user
from authority.views import manage_order
from authority.views import manage_product
from authority.views import manage_features
from authority.views import manage_banner
from authority.views import manage_faq
from authority.views import manage_businessinfo
from authority.views import manage_frontend
from authority.views import manage_sitesettings




urlpatterns = [
    path('', authority_main.AdminView.as_view(), name='authority_admin')
]

#Manage User
urlpatterns += [
    path('user-list/', manage_user.UserListView.as_view(), name='user_list'),
    path('login/', manage_user.CustomLoginView.as_view(), name='login'),
    path('logout/',  manage_user.CustomLogoutView.as_view(), name='logout'),
    path('add_admin/', manage_user.AddAdminUserView.as_view(), name='add_admin'),
    path('delete_admin/<int:pk>/', manage_user.DeleteUserView.as_view(), name='delete_admin')
]

# Manage Orders
urlpatterns += [
    path('order-list/', manage_order.OrderListView.as_view(), name='order_list'),
    path('order_details/<int:pk>/', manage_order.OrderDetailView.as_view(), name='order_details'),
    path('delete_order/<int:pk>/', manage_order.OrderDeleteView.as_view(), name='delete_order'),

]
# Manage Product
urlpatterns += [
    path('product-list/', manage_product.ProductListView.as_view(), name='product_list'),
    path('product-update/<int:pk>/', manage_product.UpdateProductView.as_view(), name='product_update'),
    path('add-product/', manage_product.AddProductView.as_view(), name='add_product'),
    path('product_delete/<int:pk>/', manage_product.ProductDeleteView.as_view(), name='product_delete'),

]

# Manage Feature
urlpatterns += [
    path('features-list/', manage_features.FeaturesListView.as_view(), name='features_list'),
    path('add_feature/', manage_features.AddFeaturesSectionView.as_view(), name='add_feature'),
    path('feature-update/<int:pk>/', manage_features.UpdateFeaturesSectionView.as_view(), name='feature_update'),
    path('feature_delete/<int:pk>/', manage_features.FeatureDeleteView.as_view(), name='feature_delete'),

]

# Manage Banners
urlpatterns += [
    path('banners-list/', manage_banner.BannerListView.as_view(), name='banners_list'),
    path('add_banner/', manage_banner.AddBannerView.as_view(), name='add_banner'),
    path('banner-update/<int:pk>/', manage_banner.UpdateBannerView.as_view(), name='update_banner'),
    path('banner_delete/<int:pk>/', manage_banner.BannerDeleteView.as_view(), name='delete_banner'),

]

# Manage FAQ
urlpatterns += [
    path('faq-list/', manage_faq.FAQListView.as_view(), name='faq_list'),
    path('add_faq/', manage_faq.AddFAQView.as_view(), name='add_faq'),
    path('faq-update/<int:pk>/', manage_faq.UpdateFAQView.as_view(), name='faq_update'),
    path('faq_delete/<int:pk>/', manage_faq.FAQDeleteView.as_view(), name='faq_delete'),
]

# Manage Businessinfo
urlpatterns += [
    path('business-list/', manage_businessinfo.BusinessInfoListView.as_view(), name='business_list'),
    path('add_business/', manage_businessinfo.AddBusinessInfoView.as_view(), name='add_business'),
    path('business-update/<int:pk>/', manage_businessinfo.UpdateBusinessInfoView.as_view(), name='business_update'),
    path('business-delete/<int:pk>/', manage_businessinfo.BusinessInfoDeleteView.as_view(), name='business_delete'),
]


# Manage Frontend Settings
urlpatterns += [
    path('frontend-settings/', manage_frontend.FrontendSettingsListView.as_view(), name='frontend_settings'),
    path('frontend-settings/add/', manage_frontend.AddFrontendSettingView.as_view(), name='add_frontend_setting'),
    path('frontend-settings/<int:pk>/update/', manage_frontend.UpdateFrontendSettingView.as_view(), name='update_frontend_setting'),
    path('frontend-settings/<int:pk>/delete/', manage_frontend.FrontendSettingDeleteView.as_view(), name='delete_frontend_setting'),
]


# Manage Site Settings
urlpatterns += [
    path('site-settings/', manage_sitesettings.SiteSettingsListView.as_view(), name='site_settings'),
    path('site-settings/add/', manage_sitesettings.AddSiteSettingView.as_view(), name='add_site_setting'),
    path('site-settings/<int:pk>/update/', manage_sitesettings.UpdateSiteSettingView.as_view(), name='update_site_setting'),
    path('site-settings/<int:pk>/delete/', manage_sitesettings.SiteSettingDeleteView.as_view(), name='delete_site_setting'),
]

authority/templates/authority_base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <title>{{ site_settings.site_name }}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <link rel="icon" href="{{ frontend_setting.favicon.url }}" type="favicon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'assets/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.png' %}">

    <!-- Template Stylesheet -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    {% if messages %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        {% for message in messages %}
            Swal.fire({
                icon: "{{ message.tags|default:'info' }}",
                title: "{{ message }}",
                confirmButtonText: "OK",
                confirmButtonColor: "#6C63FF",
                timer: 3000,  // Auto-close after 3 seconds
                showClass: { popup: '' },  // Remove show animation
                hideClass: { popup: '' }   // Remove hide animation
            });
        {% endfor %}
    });
</script>
{% endif %}

    <!-- font-aswome cdn -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://kit.fontawesome.com/ddee993d4e.js" crossorigin="anonymous"></script>
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pb-3">
            <nav class="navbar bg-light navbar-light">
            <a href="{% url 'authority:authority_admin' %}" class="navbar-brand mx-4 mb-3">


                    <img src="{{ frontend_setting.logo.url }}" alt="Admin Login Logo" style="height:60px;width:200px;">
            </a>

<!--                <div class="d-flex align-items-center ms-4 mb-4">-->
<!--                    <div class="position-relative">-->
<!--                        {% comment %} <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;"> {% endcomment %}-->
<!--                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>-->
<!--                    </div>-->
<!--                    <div class="ms-3">-->
<!--                        {% if request.user.first_name %}-->
<!--                            <h6 class="mb-0">{{request.user.first_name}} {{request.user.last_name}}</h6>-->
<!--                        {% else %}-->
<!--                            <h6 class="mb-0">{{request.user.username}}</h6>-->
<!--                        {% endif %}-->

<!--                        <span>Admin</span>-->
<!--                    </div>-->
<!--                </div>-->
                <div class="navbar-nav w-100">
                    <a href="{% url 'authority:authority_admin' %}" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
<!--                    <div class="nav-item dropdown">-->
<!--                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa-solid fa-user-plus"></i>Manage User</a>-->
<!--                        <div class="dropdown-menu bg-transparent border-0">-->
<!--                            <a href="{% url 'authority:user_list' %}" class="dropdown-item"><i class="fa-solid fa-user me-2"></i>User List</a>-->
<!--                        </div>-->
<!--                    </div>-->


                     <!-- User Link -->
                    <a href="{% url 'authority:user_list' %}" class="nav-item nav-link" style="display: flex; align-items: center;">
                        <i class="fa-solid fa-user-plus" style="margin-right: 10px; font-size: 1.2em;"></i>
                        <span>Administration</span>
                    </a>

                    <!-- Orders Link -->
                    <a href="{% url 'authority:order_list' %}" class="nav-item nav-link" style="display: flex; align-items: center;">
                        <i class="fa-solid fa-cart-plus" style="margin-right: 10px;"></i>
                        <span>Orders</span>
                    </a>

                    <!-- Features Link -->
                    <a href="{% url 'authority:features_list' %}" class="nav-item nav-link" style="display: flex; align-items: center;">
                        <i class="fa-solid fa-star" style="margin-right: 10px;"></i>
                        <span>Features</span>
                    </a>

                    <!-- Products Link -->
                    <a href="{% url 'authority:product_list' %}" class="nav-item nav-link" style="display: flex; align-items: center;">
                        <i class="fa-solid fa-box" style="margin-right: 10px;"></i>
                        <span>Products</span>
                    </a>

                    <!-- Banners Link -->
                    <a href="{% url 'authority:banners_list' %}" class="nav-item nav-link" style="display: flex; align-items: center;">
                        <i class="fa-solid fa-image" style="margin-right: 10px;"></i>
                        <span>Banners</span>
                    </a>

                <!-- FAQs Link -->
                <a href="{% url 'authority:faq_list' %}" class="nav-item nav-link" style="display: flex; align-items: center;">
                    <i class="fa-solid fa-question-circle" style="margin-right: 10px;"></i>
                    <span>FAQs</span>
                </a>

                <!-- Business Info Link -->
                <a href="{% url 'authority:business_list' %}" class="nav-item nav-link" style="display: flex; align-items: center;">
                    <i class="fa-solid fa-briefcase" style="margin-right: 10px;"></i>
                    <span>Business Info</span>
                </a>

                <!-- Front-End Settings Link -->
                <a href="{% url 'authority:frontend_settings' %}" class="nav-item nav-link" style="display: flex; align-items: center;">
                    <i class="fa-solid fa-cogs" style="margin-right: 10px;"></i>
                    <span>Front-End Settings</span>
                </a>
                    <!-- Site Settings Link -->
                <a href="{% url 'authority:site_settings' %}" class="nav-item nav-link" style="display: flex; align-items: center;">
                    <i class="fa-solid fa-sliders" style="margin-right: 10px;"></i>
                    <span>Site Settings</span>
                </a>

                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <a href="http://{{ request.get_host }}/" class="sidebar-toggler1 " data-placement="bottom" target="_blank" title="Browse Frontend">
                    <i class="fa fa-globe"></i>
                </a>

                <div class="navbar-nav align-items-center ms-auto">


                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            {% comment %} <img class="rounded-circle me-lg-2" src="img/user.jpg" alt="" style="width: 40px; height: 40px;"> {% endcomment %}
                            {% if request.user.first_name %}
                                <span class="d-none d-lg-inline-flex"> {{request.user.first_name}} {{request.user.last_name}}</span>
                            {% else %}
                                <span class="d-none d-lg-inline-flex"> {{request.user.username}}</span>
                            {% endif %}

                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="{% url 'authority:logout' %}" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->


            <!-- Blank Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row bg-light rounded  justify-content-center mx-0">
                    {% block body %}
                    {% endblock body %}
                </div>
            </div>
            <!-- Blank End -->


            {% comment %} <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Your Site Name</a>, All Right Reserved.
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End --> {% endcomment %}

    </div>


<script>
    document.addEventListener("DOMContentLoaded", function() {
        const currentPath = window.location.pathname;

        // Get all the nav-link elements
        const links = document.querySelectorAll('.navbar-nav .nav-link');

        links.forEach(link => {
            // Check if the link's href matches the current path
            if (link.getAttribute('href') === currentPath) {
                link.classList.add('active');  // Add the 'active' class
            } else {
                link.classList.remove('active');  // Remove the 'active' class from others
            }
        });
    });
</script>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'assets/lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'assets/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'assets/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'assets/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'assets/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'assets/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>